language: node_js
node_js:
- node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
scripts:
- npm test
deploy:
  provider: npm
  email: astashkinav@gmail.com
  api_key:
    secure: NPM_TOKEN
  on:
    tags: true